#!/bin/bash
set -e -u -o pipefail

# Start up using the existing init script.
# This mostly does the work keeping the service up on its own.
service mysql start

# Monitor the status periodically.
# If it returns an error, exit immediately.
while true; do
	sleep 600
	service mysql status || exit 1
done
