#!/bin/sh

# Only run this script once, not as a service.
sv once bugzilla

# Wait until the database is running & its startup has settled.
sv start mysql
sleep 10

# Move into the bugzilla directory.
cd /var/www/html/bugzilla

# Run bugzilla's checksetup normally to verify everything is behaving correctly.
# We have to call this twice because this may be a first-time run.
./checksetup.pl /etc/bugzilla/checksetup.conf
./checksetup.pl /etc/bugzilla/checksetup.conf
