#!/bin/sh

# Wait until the database is running & settled.
sv start mysql
sleep 10

# Move into the bugzilla directory.
cd /var/www/html/bugzilla

# Run bugzilla's checksetup normally to verify everything is behaving correctly.
./checksetup.pl /etc/bugzilla/checksetup.conf

# Run the jobserver.
exec ./jobqueue.pl -f start
